### PR TITLE
699: Fix issue with dismissing warnings would create a "duplicate" entry

### LINKED ISSUE #699: Discarding Warning (for URL missing) causes duplicate entry until reload
Hello,

If you get a warning for say URL missing in translated string (which happens if you localize a plugin URL) then you'll get a warning;
screen shot 2017-04-12 at 11 22 59 am

If you discard this warning then the translation becomes approved (green) but a duplicate is created which is open for editing;
screen shot 2017-04-12 at 11 33 24 am

This is minor, if you reload then the duplicate disappears, but if you were to approve the second string before reload could create some conflict (that's a presumption I didn't actually test that part).

Let me know if I can clarify or assist,
Cheers

### PR DESCRIPTION
**Pull request by toolstack**
Resolves #699.

### CODE REVIEW

File: assets/js/editor.js [hunk 1]
```diff
@@ -321,6 +322,7 @@ $gp.editor = (
 					success: function( data ) {
 						$gp.notices.success( 'Saved!' );
 						$gp.editor.replace_current( data );
+						$gp.editor.next();
```
Comment (ocean90) [inline assets/js/editor.js]: Jumping to the next editor is a bad idea because 1) a translation can have more than one warning (see #370) and 2) a translation can be in a pending state.

In both steps you'd have to re-open the previous editor for further status changes, that sounds like a step backward to me.

**Review by ocean90 — CHANGES_REQUESTED** [review]

File: assets/js/editor.js (hunk 1 above)
Comment (toolstack) [reply assets/js/editor.js]: There were two reasons I added the `next()`, first was that it called the right logic to display things correctly and second was to keep consistent with how other actions in the editor work (any time you it save, cancel, set a status, etc. the editor moves to the next entry).

I can see though in this case that may not be the desired outcome so I've updated the PR and removed some logic that was based on the assumption that whenever `replace_current()` was called that the preview would be visible (the old logic was a little redundant all things considered).

**Review by ocean90 — APPROVED** [review]

**Comment by garretthyder** [comment]
Thanks @ocean90 and @toolstack
