### PR TITLE
415: Avoid URLENCODE on the double slash paths

### LINKED ISSUE #415: Using utf8mb4 chars as names/slugs of projects can't be found
Steps to reproduce:
- Have a database which supports utf8mb4 encoding
- Create a project with 🌍 as the title

### PR DESCRIPTION
**Pull request by garretthyder**
This updates the gp_url_project urlencode implementation to avoid encoding the glossary locale URLs that contain the preceeding double slash '//'. This fixes #415 again without compromising Glossaries

I made sure to retest the original issue raised by @ocean90 in #451 so this implementation still addresses that properly.
screen shot 2018-10-30 at 3 25 03 pm

### CODE REVIEW

**Comment by garretthyder** [comment]
@toolstack The failing checks are just travis complaining about urlencode.
Looking up the difference - https://www.gyrocode.com/articles/php-urlencode-vs-rawurlencode/
Seems it's just the `~` character is encoded in `urlencode` but not `rawurlencode`, and spaces are encoded as `+` for `urlencode` but as %20.
In future if we want to look into updating this we can implement a translation module during plugin update to update the database accordingly and avoid breaking projects.

File: gp-includes/url.php [hunk 1]
```diff
@@ -146,14 +146,14 @@ function gp_url_current() {
...
 
 	// A leading double-slash will avoid prepending /projects/ to the path.
 	// This was introduced to enable linking to the locale glossary.
 	if ( '//' === substr( $project_path, 0, 2 ) ) {
-		$project_path = ltrim( $project_path, '/' );
+		$project_path = urlencode( ltrim( $project_path, '/' ) );
 	} else {
-		$project_path = array( 'projects', $project_path );
+		$project_path = array( 'projects', urlencode( $project_path ) );
 	}
```
Comment (toolstack) [inline gp-includes/url.php:158]: Let's just urlencode once, after the if condition, instead of once in each part of the if.

**Review by toolstack — CHANGES_REQUESTED** [review]

File: gp-includes/url.php (hunk 1 above)
Comment (garretthyder) [reply gp-includes/url.php:158]: How do you propose that @toolstack? The $project_path can be either a string or an array after the if statement and `urlencode` only supports strings.

Comment (toolstack) [reply gp-includes/url.php:158]: That's a good point :smile:

**Review by toolstack — APPROVED** [review]
