### PR TITLE
Translation errors

### LINKED ISSUE #1546: Disable translation warning discard for unexpected additional printf placeholders
Moved from https://meta.trac.wordpress.org/ticket/6256.

@dd32 wrote:
>  It's not too uncommon for translators to discard printf-related warnings, when they believe the warning is in error. Sometimes it is in error, but if it's not..
> 
> Unfortunately when a translator inserts extra placeholders into such a string accidentally, for example, using % within the string and not encoding it as %% it causes one of two things to happen:
>
>   -  PHP 7: String is never displayed.
>   -    PHP 8: Fatal error is encountered. Page will not render. 
>
> In both cases, having fewer placeholders in the string is okay, just not more.
> 
> Perhaps sometimes this is indeed an error in the warnings, and we should fix that, but, as plugin/theme translations go out automatically to sites we need to ensure that we never cause them to fatal due to a faulty translation.
> 
> For example:
> 
>    Original: `This is 100 percent bug free! <a href="%s">See this for proof</a>`
>    Problematic translation: `Yo! We so great! 100% bug free! <a href="%s">Check it!</a>`
>    Working translation: `Yo! We so great! 100%% bug free! <a href="%s">Check it!</a>`
>
> It's also common with URLs in translations with non-ascii characters, as %20 or similar in a URL needs to be encoded as %%20.
>
> Here's an example of an error that I've encountered on WordPress.org today while testing PHP 8.1 readiness:
>
> E_ERROR: Uncaught ArgumentCountError: 34 arguments are required, 2 given in
> 
> (34 utf8 characters in an included URL encoded as %12%34%56, etc)
>
> In reality, currently it means that in the locale in question, the This post was held for moderation by our automated system but has taken longer than expected to get approved. Please come to the #forums channel on <a href="%s">WordPress Sl.... message on their forums has never displayed correctly (or at least, not for the last year or so).

### PR DESCRIPTION
**Pull request by amieiro**
## Problem

We have some situations where we don't check some translations or if we check it, we return a warning, that can be dismissed by the translator, so the translators can add incorrect, and sometimes, dangerous translations. Some examples:
* [Incorrect placeholders](https://github.com/GlotPress/GlotPress/issues/1546). 
* [Incorrect date format](https://translate.wordpress.org/projects/wp/dev/admin/gl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=9144374&filters%5Btranslation_id%5D=70640124). 
* [Incorrect timezone format](https://translate.wordpress.org/projects/wp/dev/admin/gl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=40444&filters%5Btranslation_id%5D=105190736). 

Fixes https://github.com/GlotPress/GlotPress/issues/1546.

## Solution

This PR adds two classes, to be able to add some checks in the GlotPress core, and another ones in an external plugin, because sometimes the error checks are very specific to the project (e.g., WordPress core).

This PR adds in the core the [Incorrect placeholder check](https://github.com/GlotPress/GlotPress/issues/1546). 

The end users will receive an error, so they can't dismiss the message, so with this update we will be sure that we check some big translation problems and the translator can't dismiss the message.

## To-do

- [ ] Create an external plugin, at translate.w.org, to add some checks for the WordPress core:
    - Check the unexpected timezone.
    - Check the unexpected start of the week.
    - Check the unexpected date format (year, month, day).
    - ...

## Testing Instructions

Before start testing, please, compile the assets executing:

```
npm install
npm run build
```

This PR add some unit tests in the `tests/phpunit/testcases/test_builtin_errors.php` file. To execute only these tests, you cas run 

`phpunit --filter GP_Test_Builtin_Translation_Errors
`

To execute all the tests, you can run

`phpunit` 

To test the *incorrect placeholder check* in the UI, you can:
1. Open an original string in a project.
2.  Add the `Yo! We so great! 100% bug free! <a href="%s">Check it!</a>` translation.
3. Click on the "Add translation" or "Suggest" button, depending on your role.
4. You will get an error in the UI and you can't save the translation.

image

### CODE REVIEW

**Review by trymebytes — DISMISSED** [review]
Tested and works as expected!

File: gp-includes/errors.php [hunk 1]
```diff
@@ -0,0 +1,188 @@
...
+				// % is included for escaped %%.
+				if ( '' === $char || false === strpos( 'bcdefgosux%l.', $char ) ) {
+					$unexpected_tokens[] = $m[0][ $i ];
+				}
+			}
+		}
+		if ( $unexpected_tokens ) {
+			return sprintf(
+			/* translators: %s: Placeholders. */
+				esc_html__( 'The translation contains the following unexpected placeholders: %s', 'glotpress' ),
```
Comment (akirk) [inline gp-includes/errors.php]: The escaping should not happen here but upon output (maybe this is to be output in the CLI?)

**Review by akirk — APPROVED** [review]
