### PR TITLE
979: Fix multi-select for forward and backwards selections.

### LINKED ISSUE #979: Multi-check functionality only works forward and not backwards
Hello,

The multi-select function of checkboxes only works going down the page and not back up. By the multi-select function I speak on when you check a checkbox and then skip a few rows and check another checkbox then all checkboxes in between become checked. The code for this;
https://github.com/GlotPress/GlotPress-WP/blob/43bb5383e114835b09fc47c727d06e6d3ca8114e/assets/js/translations-page.js#L47-L68

This only works from top to bottom, it would be nice if it worked in reverse as well so if you check a box low in the page and then go up and check another then all boxes in between get checked.

How it functions going down the page;
Multi-Check Downwards

Going in reverse this illustrates how it doesn't check the boxes in between;
Failed Multi-Check Upwards

Hope that makes sense,
Cheers

### PR DESCRIPTION
**Pull request by toolstack**
Updated from WP common.js to commit 25141.

Resolves #979.

### CODE REVIEW

File: assets/js/translations-page.js [hunk 1]
```diff
@@ -45,8 +45,10 @@ jQuery(function($) {
 	});
 
 	var lastClicked = false;
-	// Check all checkboxes from WP common.js, synced with [20400]
+	// Check all checkboxes from WP common.js, synced with [25141]
 	$('tbody').children().children('.checkbox').find(':checkbox').click( function(e) {
+		var checks, first, last, sliced;
```
Comment (garretthyder) [inline assets/js/translations-page.js]: `checked` should be declared as well

File: assets/js/translations-page.js [hunk 2]
```diff
@@ -45,8 +45,10 @@ jQuery(function($) {
...
+
```
Comment (garretthyder) [inline assets/js/translations-page.js:51]: line can be removed

**Review by garretthyder — COMMENTED** [review]
Thanks @toolstack works like a charm.
In the origin code I noticed a check all feature;
https://core.trac.wordpress.org/browser/trunk/src/wp-admin/js/common.js?rev=25141#L300
*Should this be a unique ticket?

File: assets/js/translations-page.js (hunk 2 above)
Comment (toolstack) [reply assets/js/translations-page.js:51]: Can be, but it's more readable to separate the vars from the code.  When the file's min'd it will get deleted anyway.

File: assets/js/translations-page.js (hunk 1 above)
Comment (toolstack) [reply assets/js/translations-page.js]: Hmmm... interesting that the code sniffer didn't pick it up like the others, I'll add it..

File: assets/js/translations-page.js (hunk 2 above)
Comment (garretthyder) [reply assets/js/translations-page.js:51]: Good point

**Review by garretthyder — APPROVED** [review]
Thanks @toolstack 
I opened the other item mentioned as a new ticket - https://github.com/GlotPress/GlotPress-WP/issues/981
Also I noticed in core they switched to delegate the click in core#37973 so opened a ticket to continue maintaining parity with core - https://github.com/GlotPress/GlotPress-WP/issues/982
