### PR TITLE
Glossary: Add new validation methods to validate terms

### LINKED ISSUE #1363: PHP notice when adding a glossary entry with trailing whitespace
To reproduce:

* Go to a glossary
* Enter a new term with trailing whitespace
* Enter translation
* Submit entry

```
Notice: Undefined offset: 0 in /var/www/html/wp-content/plugins/glotpress/gp-includes/routes/glossary-entry.php on line 85

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/glotpress/gp-includes/routes/glossary-entry.php:85) in /var/www/html/wp-content/plugins/glotpress/gp-includes/misc.php on line 482

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/glotpress/gp-includes/routes/glossary-entry.php:85) in /var/www/html/wp-includes/pluggable.php on line 1340

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/glotpress/gp-includes/routes/glossary-entry.php:85) in /var/www/html/wp-includes/pluggable.php on line 1343

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/glotpress/gp-includes/routes/glossary-entry.php:85) in /var/www/html/wp-content/plugins/glotpress/gp-includes/route.php on line 349
Redirecting to: /glotpress/projects/wordpress/de/default/glossary/...
```

Introduced in #770.

### PR DESCRIPTION
**Pull request by ocean90**
Fixes #1363.

Move the current check into two validation methods to get more helpful error messages:

* The field term is invalid and should be starting and ending with a word character!
* The field term is invalid and should be consisting only of ASCII characters!

Previous message: "Glossary terms cannot contain word break or multi-byte characters!"

Hide whitespace changes for easier review: https://github.com/GlotPress/GlotPress-WP/pull/1364/files?w=1

### CODE REVIEW

**Comment by pedro-mendonca** [comment]
@ocean90 the error message `The field term is invalid and should be starting or ending with a word character!` would be better as `(...) should start and end with word characters!`

**Comment by ocean90** [comment]
@pedro-mendonca I kind of agree but that's how the current error message are generated: https://github.com/GlotPress/GlotPress-WP/blob/51d7c3b1275684b3befd2dcc89f6f40ef5c127f8/gp-includes/validation.php#L181-L198

**Comment by pedro-mendonca** [comment]
For now it only need renaming all `starting_or_ending_with_a_word_character` to `starting_and_ending_with_a_word_character`.
I'm working on a way to add i18n to these messages.

File: gp-includes/misc.php [hunk 1]
```diff
@@ -447,6 +447,30 @@ function gp_is_one_of( $value, $list ) {
...
+
+/**
+ * Checks if the passed value starts and end with a word character.
+ *
+ * @since 3.0.0
+ *
+ * @param string $value The value you want to check.
+ * @return bool
+ */
+function gp_is_starting_or_ending_with_a_word_character( $value ) {
```
Comment (pedro-mendonca) [inline gp-includes/misc.php]: Rename to `gp_is_starting_and_ending_with_a_word_character` to fix error message.

File: gp-includes/things/glossary-entry.php [hunk 2]
```diff
@@ -79,6 +79,8 @@ private function setup_pos() {
 	 */
 	public function restrict_fields( $rules ) {
 		$rules->term_should_not_be( 'empty' );
+		$rules->term_should_be( 'consisting_only_of_ASCII_characters' );
+		$rules->term_should_be( 'starting_or_ending_with_a_word_character' );
```
Comment (pedro-mendonca) [inline gp-includes/things/glossary-entry.php]: Rename to `starting_and_ending_with_a_word_character` to fix error message.

File: gp-includes/validation.php [hunk 3]
```diff
@@ -226,3 +226,5 @@ public static function get( $key ) {
 GP_Validators::register( 'between', 'gp_is_between' );
 GP_Validators::register( 'between_exclusive', 'gp_is_between_exclusive' );
 GP_Validators::register( 'one_of', 'gp_is_one_of' );
+GP_Validators::register( 'consisting_only_of_ASCII_characters', 'gp_is_ascii_string' );
+GP_Validators::register( 'starting_or_ending_with_a_word_character', 'gp_is_starting_or_ending_with_a_word_character' );
```
Comment (pedro-mendonca) [inline gp-includes/validation.php]: Rename to `starting_and_ending_with_a_word_character`  and `gp_is_starting_and_ending_with_a_word_character` to fix error message.

File: tests/phpunit/testcases/test_validation.php [hunk 4]
```diff
@@ -63,4 +63,27 @@ function test_one_of() {
...
+		$this->assertEquals( true, $f( 'a' ) );
+		$this->assertEquals( true, $f( 'AbC' ) );
+		$this->assertEquals( true, $f( 'foo bar' ) );
+		$this->assertEquals( true, $f( '&' ) );
+		$this->assertEquals( true, $f( '123abc' ) );
+		$this->assertEquals( false, $f( 'äbc' ) );
+		$this->assertEquals( false, $f( 'ãbc' ) );
+	}
+
+	function test_is_starting_or_ending_with_a_word_character() {
```
Comment (pedro-mendonca) [inline tests/phpunit/testcases/test_validation.php]: Rename to `test_is_starting_and_ending_with_a_word_character` to fix error message.

**Review by pedro-mendonca — APPROVED** [review]
