### PR TITLE
1169: Fix Glossary Tooltip to match terms with multiple words and words with hyphens

### LINKED ISSUE #1169: Glossary tooltip not showing for some words
Italian Polyglots are observing some missing tooltip from our Italian glossary in translate.wordpress.org platform.

At a first check it seems a problem of expression composed by more words and for words with "-" in them.

Some examples:

"accent" is ok, 
but "accent color" is not ok 
string example: https://translate.wordpress.org/projects/wp-themes/atomic-blocks/it/default/?filters[status]=either&filters[original_id]=6319157&filters[translation_id]=57301288)

"pre-package" is not ok 
string example: https://translate.wordpress.org/projects/wp-themes/zerif-lite/it/default/?filters[status]=either&filters[original_id]=241477&filters[translation_id]=55769101

Thanks, Lidia

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Summary of the improvements:

- [x] Don't add suffixes to terms with **multiple words** (eg: `color scheme`) - https://github.com/GlotPress/GlotPress-WP/commit/98c4bf9043e45693f50a17bb02163e7a75172e59
- [-] ~Add suffixes for words ending with **e** (eg: `delet[ed]`, `delet[ion]`, `delet[ing]` ) - https://github.com/GlotPress/GlotPress-WP/commit/c6b7519b66a3f6ec3fbbf17983d5088e27e84895~ (reverted to add in another PR)
- [x] Sort by word count and alphabetically, to first search terms with **muiltiple words** and **words with hyphens** https://github.com/GlotPress/GlotPress-WP/commit/b7a1b948a9ac2d97113a1d4d4d06273c087ae138, https://github.com/GlotPress/GlotPress-WP/commit/cf5a8a4dd97fe4f9105636cf86dd2ed2d9cd4a25 and https://github.com/GlotPress/GlotPress-WP/pull/1359/commits/2e2b234cf2ce69f4c7f8402905ac39ebfa8ce4ab
  Search priorities:
  - Priority 1:
    - `admin color scheme`
  - Priority 2:
    - `admin color`
    - `color scheme`
    - `color-scheme`
  - Priority 3:
    - `color`
    - `scheme`

Fixes #1169

### CODE REVIEW

File: gp-templates/helper-functions.php [hunk 1]
```diff
@@ -166,10 +197,10 @@ function map_glossary_entries_to_translation_originals( $translation, $glossary,
 		$escaped_chunk = esc_translation( $chunk );
 
 		// Create a lower case version to compare with the glossary terms.
-		$lower_chunk = strtolower( $chunk );
+		$lower_chunk = strtolower( preg_quote( $chunk, '/' ) );
 
 		// Search the glossary terms for a matching entry.
-		if ( false !== array_search( $lower_chunk, $glossary_entries_terms_array, true ) ) {
+		if ( in_array( $lower_chunk, $glossary_entries_terms_array ) ) {
```
Comment (ocean90) [inline gp-templates/helper-functions.php]: Why is this no longer a strict check?

File: gp-templates/helper-functions.php [hunk 2]
```diff
@@ -156,8 +169,26 @@ function map_glossary_entries_to_translation_originals( $translation, $glossary,
...
+			$b_words = preg_split( '/[\s-]/', $b );
+			return count( $b_words ) <=> count( $a_words );
+		}
+	);
+
+	// Set terms search string.
+	$terms_search = array();
+	foreach ( $glossary_entries_terms_array as $term ) {
+		// Add word boundaries to search term.
+		$terms_search[] = '(\b' . $term . '\b)';
```
Comment (ocean90) [inline gp-templates/helper-functions.php]: Is there a `preg_quote()` missing?

**Review by ocean90 — COMMENTED** [review]
Thanks for working for this!

Could you please add some test cases to [GP_Test_Template_Helper_Functions](https://github.com/GlotPress/GlotPress-WP/commits/develop/tests/phpunit/testcases/test_template_helper_functions.php) for this?
It seems like c6b7519b66a3f6ec3fbbf17983d5088e27e84895 is unrelated to this bugfix. This should be a separate pull request.

File: gp-templates/helper-functions.php (hunk 2 above)
Comment (pedro-mendonca) [reply gp-templates/helper-functions.php]: There was already a preg_quote() on https://github.com/GlotPress/GlotPress-WP/blob/develop/gp-templates/helper-functions.php#L89 that processes all the terms in the array. Would it be better to use it immediatly before the search?

File: gp-templates/helper-functions.php (hunk 1 above)
Comment (pedro-mendonca) [reply gp-templates/helper-functions.php]: Fixed in https://github.com/GlotPress/GlotPress-WP/pull/1359/commits/0c7959d8030d1207da5de831b840a342b8025d40

File: gp-templates/helper-functions.php (hunk 2 above)
Comment (pedro-mendonca) [reply gp-templates/helper-functions.php]: I can edit it and only preg_quote immediatly before the search, but have to remove all the preg_quote()s on gp_sort_glossary_entries_terms().
It keeps the code simpler, should I go for it?

Comment (pedro-mendonca) [reply gp-templates/helper-functions.php]: I've done it in https://github.com/GlotPress/GlotPress-WP/pull/1359/commits/f5b86cdf21279213fa2247986484261dfb1e3bda
Looks cleaner, let me know if it's ok for you.

**Comment by pedro-mendonca** [comment]
@ocean90 I've added some test cases

File: gp-templates/helper-functions.php (hunk 2 above)
Comment (ocean90) [reply gp-templates/helper-functions.php]: Yes, thank you!

**Review by ocean90 — APPROVED** [review]
