### PR TITLE
Fix Pirate locale code and slug to character length

### LINKED ISSUE #891: Slug of Pirate locale doesn't fit into `locale` column size
The `locale` column of the translation set only allows 10 characters. Pirate has 11 with `art-xpirate` so it only gets stored as `art-xpirat`.

Two options: Increase column size of `locale` field or change the `slug`  property of the `GP_Locale` to something shorter like `pirate`.

### PR DESCRIPTION
**Pull request by danieltj27**
Fixes #891.

> The locale column of the translation set only allows 10 characters. Pirate has 11 with art-xpirate so it only gets stored as art-xpirat.

This fixes the issue by changing the locale code and slug to `xx-pirate` to match the Google locale code instead so it's sorted and not cut off.

### CODE REVIEW

**Comment by danieltj27** [comment]
I've fixed the conflicts the original PR commit was causing. Hopefully the CI test passes!

File: locales/locales.php [hunk 1]
```diff
@@ -1666,8 +1666,8 @@ public function __construct() {
 		$pirate->english_name = 'English (Pirate)';
 		$pirate->native_name = 'English (Pirate)';
 		$pirate->lang_code_iso_639_2 = 'art';
-		$pirate->wp_locale = 'art_xpirate';
-		$pirate->slug = 'art-xpirate';
+		$pirate->wp_locale = 'xx_pirate';
+		$pirate->slug = 'xx-pirate';
```
Comment (ocean90) [inline locales/locales.php]: Only the slug needs to be changed, the WP locale should remain as is.

xx-pirate looks odd, let’s just use pirate.

**Review by ocean90 — CHANGES_REQUESTED** [review]

**Comment by danieltj27** [comment]
@ocean90 I've updated the changes so it's just the slug that has changed now 👍

**Review by ocean90 — APPROVED** [review]
