### PR TITLE
Fix fatal error in PHP8.x for invalid get data

### LINKED ISSUE #1753: Warning (PHP7) / Fatal (PHP8) triggered by user inputs in gp_array_get()
## Description

Similar to #1749, this time a warning/fatal in `gp_array_get()` triggered by unexpected user inputs.

> PHP 7.4 E_WARNING: Illegal offset type in isset or empty in wp-content/plugins/glotpress/gp-includes/misc.php:66
> PHP 8.1  Fatal error: Uncaught Error: Illegal offset type in isset or empty in wp-content/plugins/glotpress/gp-includes/misc.php on line 66

## Step-by-step reproduction instructions

Using some unexpected inputs in GET, it's possible to trigger the above warning/fatal.

> GET https://example.org/projects/example-project/en-au/default/?sort[by][foobar]=1

This can be simulated in a unit test as such:

```
var_dump( gp_array_get( [], [ 'foobar' => 1 ] ) );
```

Code ref:
https://github.com/GlotPress/GlotPress/blob/bd1b5f298072b15fa122a6d12403553e99b5b365/gp-includes/misc.php#L65-L67

Interestingly `gp_member_get()` doesn't suffer the same fatal, but can trigger a Warning:
```
gp_member_get( new stdClass, [ 'foobar' => 1 ] );

Warning: Array to string conversion in wp-content/plugins/glotpress/gp-includes/misc.php on line 83
```

https://github.com/GlotPress/GlotPress/blob/bd1b5f298072b15fa122a6d12403553e99b5b365/gp-includes/misc.php#L82-L84

I didn't immediately see any other issues in those helper methods.

### PR DESCRIPTION
**Pull request by amieiro**
## Problem

A malformed sort array throws a fatal error in PHP 8.x (in PHP 7.4 throws a warning).

Before this fix, if you add `?sort[by][foobar]=1` to a GlotPress URL, in a GET request, you will get an `error 500`.  

#### Before 

```
wget -S https://glotpress.test/glotpress/projects/local-plugins/glotpress/gl/default/\?sort\[by\]\[foobar\]\=1
...
HTTP request sent, awaiting response...
  HTTP/1.1 500 Internal Server Error
```

#### After 

```
wget -S https://glotpress.test/glotpress/projects/local-plugins/glotpress/gl/default/\?sort\[by\]\[foobar\]\=1
...
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
```

Fixes https://github.com/GlotPress/GlotPress/issues/1753.

## Solution

The malformed URL throws an error at `wp-content/plugins/GlotPress/gp-includes/misc.php on line 66` because the `$key` parameter in the `gp_array_get()` function is an array. This PR checks if the `$key` is a string or a number before using it as key in the array.
 
After solving this first problem, it arises another warning:

```
PHP Warning:  Array to string conversion in wp-content/plugins/GlotPress/gp-templates/translations.php on line 135
PHP Warning:  Array to string conversion in wp-content/plugins/GlotPress/gp-templates/translations.php on line 149
PHP Warning:  Array to string conversion in wp-content/plugins/GlotPress/gp-templates/translations.php on line 163
PHP Warning:  Array to string conversion in wp-content/plugins/GlotPress/gp-templates/translations.php on line 177
PHP Warning:  Array to string conversion in wp-content/plugins/GlotPress/gp-templates/translations.php on line 191
PHP Warning:  Array to string conversion in wp-content/plugins/GlotPress/gp-templates/translations.php on line 207
PHP Warning:  Array to string conversion in wp-content/plugins/GlotPress/gp-templates/translations.php on line 221
```
This problem is solved removing the values from the filters that are not strings or numbers.

### CODE REVIEW

File: gp-includes/misc.php [hunk 1]
```diff
@@ -63,7 +63,7 @@ function gp_route_nonce_url( $url, $action ) {
  * @return mixed $array[$key] if exists or $default
  */
 function gp_array_get( $array, $key, $default = '' ) {
-	return isset( $array[ $key ] ) ? $array[ $key ] : $default;
+	return ( is_string( $key ) || is_numeric( $key ) ) && isset( $array[ $key ] ) ? $array[ $key ] : $default;
```
Comment (dd32) [inline gp-includes/misc.php]: You could probably use `is_scalar()` instead if you wanted something shorter:

A personal preference is to use brackets around the terninary operator when multiple function calls are present too:

```suggestion
	return ( is_scalar( $key ) && isset( $array[ $key ] ) ) ? $array[ $key ] : $default;
```

File: gp-templates/translations.php [hunk 2]
```diff
@@ -105,6 +105,13 @@
 		$filters_values_only = array_filter( $filters );
 		$sort_values_only    = array_filter( $sort );
 		$filters_and_sort    = array_merge( $filters_values_only, $sort_values_only );
+		// Remove any non-string or non-numeric values from the array.
+		$filters_and_sort    = array_filter(
+			$filters_and_sort,
+			function ( $value ) {
+				return is_string( $value ) || is_numeric( $value );
+			}
+		);
```
Comment (dd32) [inline gp-templates/translations.php]: Similar to above, this can be simplified to scalar with:

```suggestion
		$filters_and_sort    = array_filter( $filters_and_sort, 'is_scalar' );
```

**Review by dd32 — DISMISSED** [review]

File: gp-templates/translations.php (hunk 2 above)
Comment (amieiro) [reply gp-templates/translations.php]: @dd32 Thank you for the feedback! I have committed your suggestions. Can you re-approve the PR another time? Thank you!

File: gp-includes/misc.php [hunk 3]
```diff
@@ -80,7 +80,7 @@ function gp_const_set( $name, $value ) {
 
 
 function gp_member_get( $object, $key, $default = '' ) {
-	return isset( $object->$key ) ? $object->$key : $default;
+	return is_string( $key ) && property_exists( $object, $key ) ? $object->$key : $default;
```
Comment (trymebytes) [inline gp-includes/misc.php]: We could wrap this in brackets too.

```suggestion
	return ( is_string( $key ) && property_exists( $object, $key ) ) ? $object->$key : $default;
```

**Review by trymebytes — DISMISSED** [review]
I left a tiny comment but looks good to me!

**Review by trymebytes — APPROVED** [review]
