### PR TITLE
Glossary: Fix fatal array in PHP8 for invalid post data

### LINKED ISSUE #1749: Warning/Fatal due to pentesting payloads
## Description
It's not uncommon for automated tools to submit lots of bogus data to various endpoints, unfortunately some GlotPress endpoints appear not to sanitize their inputs appropriately and assume the structure received is correct.

One such instance of this is the following Warning in PHP 7.4, which is a Fatal in 8.1:
```
PHP 7.4: E_WARNING: array_shift() expects parameter 1 to be array, string given in wp-content/plugins/glotpress/gp-includes/routes/glossary-entry.php:110

PHP 8.1: Fatal error:  Uncaught TypeError: array_shift(): Argument #1 ($array) must be of type array, string given in wp-content/plugins/glotpress/gp-includes/routes/glossary-entry.php:110
```

https://github.com/GlotPress/GlotPress/blob/5d547417bce54e897e00dc6b45ecd502a0442668/gp-includes/routes/glossary-entry.php#L108-L111

## Step-by-step reproduction instructions
POST https://example.org/locale/en-au/default/glossary/
glossary_entry=foobar&bogus=data

## Expected behavior
An error of `The glossary entry cannot be found` or `An error has occurred. Please try again.`

## Actual behavior
A PHP Warning + the above errors, OR a fatal error.

## Screenshots or screen recording (optional)

Duplication:
```
$ curl https://php81.example.org/locale/en-au/default/glossary/ --data 'glossary_entry=foobar&bogus=data' -i
HTTP/1.1 500 Internal Server Error

$ curl https://php74.example.org/locale/en-au/default/glossary/ --data 'glossary_entry=foobar&bogus=data'
HTTP/1.1 200 OK
...
The glossary entry cannot be found
```

## WordPress information
- WordPress version: 
- GlotPress version: 
- Are all plugins except GlotPress deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-Three)? 

## Device information
- Operating system: 
- Browser:

### PR DESCRIPTION
**Pull request by akirk**
Fixes #1749.

## Before
```
$ curl https://php81.example.org/locale/en-au/default/glossary/ --data 'glossary_entry=foobar&bogus=data' -i
HTTP/1.1 500 Internal Server Error

$ curl https://php74.example.org/locale/en-au/default/glossary/ --data 'glossary_entry=foobar&bogus=data'
HTTP/1.1 200 OK
...
The glossary entry cannot be found
```

## After

```
$ curl https://php81.example.org/locale/en-au/default/glossary/ --data 'glossary_entry=foobar&bogus=data' -i
HTTP/1.1 404 Not Found

$ curl https://php74.example.org/locale/en-au/default/glossary/ --data 'glossary_entry=foobar&bogus=data'
HTTP/1.1 404 Not Found
...
The glossary entry cannot be found
```

### CODE REVIEW

**Review by trymebytes — DISMISSED** [review]
Looks good to me!

File: gp-includes/routes/glossary-entry.php [hunk 1]
```diff
@@ -106,12 +106,16 @@ public function glossary_entry_add_post( $project_path, $locale_slug, $translati
 	}
 
 	public function glossary_entries_post( $project_path, $locale_slug, $translation_set_slug ) {
-		$ge_post        = gp_post( 'glossary_entry' );
+		$ge_post = gp_post( 'glossary_entry' );
+		if ( ! is_array( $ge_post ) || ! isset( $ge_post[0]['glossary_entry_id'] ) ) {
```
Comment (amieiro) [inline gp-includes/routes/glossary-entry.php]: The `glosary_entries_post` method is used to update an individual entry in the glossary. When I test this change and I try to update an entry, I get this error:

image

This is because this PR tries to check the "0" element in the array, but the key in the array is the `glossary_entry_id `.  E.g.:

```
array(1) { [5]=> array(6) { ["term"]=> string(1) "&" ["part_of_speech"]=> string(4) "noun" ["translation"]=> string(1) "&" ["comment"]=> string(0) "" ["glossary_id"]=> string(1) "1" ["glossary_entry_id"]=> string(1) "5" } }
```
This change solves this problem:

```suggestion
		if ( ! is_array( $ge_post ) || ! isset( reset($ge_post)['glossary_entry_id'] ) ) {
```

**Review by amieiro — CHANGES_REQUESTED** [review]

File: gp-includes/routes/glossary-entry.php (hunk 1 above)
Comment (akirk) [reply gp-includes/routes/glossary-entry.php]: Thanks, I don't think it's a good idea to use `reset` inside an `isset` but I have committed new code that separates out the checks which should work better.

**Review by amieiro — APPROVED** [review]

**Comment by amieiro** [comment]
Now, it works fine for me.
