### PR TITLE
[1813] Fix errors when URL parameters like "filter[status]" aren't strings

### LINKED ISSUE #1813: Cascading warnings from input on array functions
## Description
Cascading warnings from input on array functions.

Many hundreds of these happen each day, so it creates unnecessary noise in the dotorg warnings channels.

## Step-by-step reproduction instructions
```
E_WARNING: explode() expects parameter 2 to be string, array given in [..]/wp-content/plugins/glotpress/gp-templates/translations.php:290
```

```
E_WARNING: in_array() expects parameter 2 to be array, null given in [..]/wp-content/plugins/glotpress/gp-templates/translations.php:293
```

The above warning then runs on L297, 301, 305, 309, 314, 319

## Expected behavior
No warnings should appear when values isn't an array.

## WordPress information
- WordPress version: trunk (wp.org)
- GlotPress version: latest committed version to wp.org

### PR DESCRIPTION
**Pull request by pedro-mendonca**
## Problem

If the translations filter in the URL parameter sends an array, for example `...?filters[status][0]=current&filters[status][1]=fuzzy`, the `gp_array_get( $filters, 'status', 'current_or_waiting_or_fuzzy_or_untranslated' )` will return an array instead of a string.
This errors on subsequent `explode( '_or_', $selected_status )`.

## Solution

If the statuses set on URL get parameters are not the predictable ones, fallback to ~the `current_or_waiting_or_fuzzy_or_untranslated`~ **an empty** string.

## Testing Instructions
1. Open a translation set.
2. Change the default `...?filters[status]=current_or_fuzzy` URL parameters to `...?filters[status][0]=current&filters[status][1]=fuzzy`
3. See the errors. 

Fixes #1813

### CODE REVIEW

**Comment by amieiro** [comment]
I am testing this PR in 2 installations, one with PHP7.4 and another with PHP8.0. In PHP7.4 I get warnings, but in PHP8.0 I get 
fatal errors.

I am using this GET string to test this PR:
```
?filters%5Bstatus%5D=untranslated&filters%5Bstatus%5D%5Bwaiting%5D=fc7e06db
```

I suggest one new check, to resolve some notices I get with PHP7.4:

```
PHP Notice:  Array to string conversion in wp-content/plugins/GlotPress/gp-templates/translations.php on line 135
PHP Notice:  Array to string conversion in wp-content/plugins/GlotPress/gp-templates/translations.php on line 149
PHP Notice:  Array to string conversion in wp-content/plugins/GlotPress/gp-templates/translations.php on line 163
PHP Notice:  Array to string conversion in wp-content/plugins/GlotPress/gp-templates/translations.php on line 177
PHP Notice:  Array to string conversion in wp-content/plugins/GlotPress/gp-templates/translations.php on line 191
PHP Notice:  Array to string conversion in wp-content/plugins/GlotPress/gp-templates/translations.php on line 207
PHP Notice:  Array to string conversion in wp-content/plugins/GlotPress/gp-templates/translations.php on line 221

```

In the `gp-templates/translations.php` we need to filter the values in the `$filters_values_only` that are not strings. I suggest to change 

```
		$filters_values_only = array_filter( $filters );
```

to
 
```
		$filters_values_only = array_map(function($value) {
			return is_string($value) ? $value : '';
		}, $filters_values_only);
```

**Comment by pedro-mendonca** [comment]
The problem is more vast, unfortunately not only the key `$filters[status]` has this problem.
The same problem can easily occur with both `$filters` array and `$sort` since `gp_get( 'filters' )` and `gp_get( 'sort' )` in `translations.php` route.

To fix it, I propose sanitize it immediatly after the `gp_get()`.

File: gp-includes/routes/glossary.php [hunk 1]
```diff
@@ -15,8 +15,19 @@
...
 
 	public function new_get() {
-		$glossary                     = new GP_Glossary();
-		$glossary->translation_set_id = gp_get( 'translation_set_id' );
+		$glossary = new GP_Glossary();
+
+		$translation_set_id = gp_get( 'translation_set_id' );
+
+		// Make sure 'translation_set_id' is a string and convert to int ID. Defaults to null.
+		$translation_set_id = is_string( $translation_set_id ) && intval( $translation_set_id ) ? intval( $translation_set_id ) : null;
```
Comment (amieiro) [inline gp-includes/routes/glossary.php]: I have used some different GET parameters, and we have a problem with the strings starting with a number. E.g., if the pamater is `1234www`, the `intval` function returns `1234`, so we need to change it:

- `/glotpress/glossaries/-new/?translation_set_id=fasdf` 
- `/glotpress/glossaries/-new/?translation_set_id=123`
- `/glotpress/glossaries/-new/?translation_set_id=1s`
- `/glotpress/glossaries/-new/?translation_set_id[]=1`
- `/glotpress/glossaries/-new/?translation_set_id[1]=1ss`
- `/glotpress/glossaries/-new/?translation_set_id=1234www`
```suggestion
		$translation_set_id = filter_var( $translation_set_id, FILTER_VALIDATE_INT ) !== false ? intval( $translation_set_id ) : null;
```

File: gp-includes/routes/project.php [hunk 2]
```diff
@@ -288,9 +288,13 @@ public function delete_get( $project_path ) {
...
-		$project                    = new GP_Project();
-		$project->active            = 1;
-		$project->parent_project_id = gp_get( 'parent_project_id', null );
+		$project         = new GP_Project();
+		$project->active = 1;
+
+		$parent_project_id = gp_get( 'parent_project_id' );
+
+		// Make sure 'parent_project_id' is a string and convert to int ID. Defaults to null.
+		$project->parent_project_id = is_string( $parent_project_id ) && intval( $parent_project_id ) ? intval( $parent_project_id ) : null;
```
Comment (amieiro) [inline gp-includes/routes/project.php]: Same problem here. I have tested it with these GET parameters:

- `/glotpress/projects/-new/`
- `/glotpress/projects/-new/?parent_project_id=146`
- `/glotpress/projects/-new/?parent_project_id=1ss`
- `/glotpress/projects/-new/?parent_project_id[]=146`
- `/glotpress/projects/-new/?parent_project_id[1]=1ss`
- `/glotpress/projects/-new/?parent_project_id==1234www`
- `/glotpress/projects/-new/?parent_project_id==abxss-_1`

```suggestion
		$project->parent_project_id = filter_var( $parent_project_id, FILTER_VALIDATE_INT ) !== false ? intval( $parent_project_id ) : null;
```

File: gp-includes/routes/translation-set.php [hunk 3]
```diff
@@ -14,9 +14,13 @@
...
 class GP_Route_Translation_Set extends GP_Route_Main {
 	public function new_get() {
-		$set             = new GP_Translation_Set();
-		$set->project_id = gp_get( 'project_id' );
-		$project         = $set->project_id ? GP::$project->get( $set->project_id ) : null;
+		$set        = new GP_Translation_Set();
+		$project_id = gp_get( 'project_id' );
+
+		// Make sure 'project_id' is a string and convert to int ID. Defaults to null.
+		$set->project_id = is_string( $project_id ) && intval( $project_id ) ? intval( $project_id ) : null;
```
Comment (amieiro) [inline gp-includes/routes/translation-set.php]: Same problem here. I have tested it with these GET parameters:

- `/glotpress/sets/-new/?project_id=fasdf`
- `/glotpress/sets/-new/?project_id=123`
- `/glotpress/sets/-new/?project_id=1s`
- `/glotpress/sets/-new/?project_id[]=1`
- `/glotpress/sets/-new/?project_id[1]=1ss`
- `/glotpress/sets/-new/?project_id=1234www`

```suggestion
		$set->project_id = filter_var( $project_id, FILTER_VALIDATE_INT ) !== false ? intval( $project_id ) : null;
```

File: gp-includes/routes/project.php (hunk 2 above)
Comment (pedro-mendonca) [reply gp-includes/routes/project.php]: I'm making it more simpler with `is_numeric()`.

File: gp-includes/routes/glossary.php (hunk 1 above)
Comment (pedro-mendonca) [reply gp-includes/routes/glossary.php]: As we've came to the conclusion in Slack, I'm making it more simpler with `is_numeric()`.

File: gp-includes/routes/translation-set.php (hunk 3 above)
Comment (pedro-mendonca) [reply gp-includes/routes/translation-set.php]: I'm making it more simpler with `is_numeric()`.

**Comment by pedro-mendonca** [comment]
In https://github.com/GlotPress/GlotPress/pull/1814/commits/1e294de20612cbd97142ae81869e7874c16ea008 I've updated the check for the int values sent through `gp_get()` with `is_numeric()`.

**Review by amieiro — APPROVED** [review]
