### PR TITLE
924: Glossary view: Fix closing dt element

### LINKED ISSUE #924: Glossary view page contains unclosed dt tag
The template `gp-templates/glossary-view.php` [contains an unclosed](https://github.com/GlotPress/GlotPress-WP/blob/develop/gp-templates/glossary-view.php#L71) `<dt`> element, which has the potential to causing rendering issues in some browsers.

**Note**: Addressed in PR: #923 

Thanks!

### PR DESCRIPTION
**Pull request by ramonjd**
This PR resolves #924 by correcting an unclosed `<dt>` tag in the glossary view.

screen shot 2018-09-12 at 4 14 04 pm

### CODE REVIEW

**Review by Mte90 — APPROVED** [review]

**Comment by toolstack** [comment]
Hi @ramonjd, thanks for the PR.  Could you do two items for us: 
- open an associated issue with the details 
- Fix the PHPCS error

Thanks.

**Comment by ramonjd** [comment]
@toolstack 

> open an associated issue with the details

All done. Issue: #924 

I'll read the contrib docs first next time. :) Apologies!

**Comment by toolstack** [comment]
@ramonjd Thanks.

File: gp-templates/glossary-view.php [hunk 1]
```diff
@@ -68,7 +68,7 @@
 
 				<form action="<?php echo esc_url( gp_url_join( $url, '-new' ) ); ?>" method="post">
 					<dl>
-						<dt><label for="new_glossary_entry_term"><?php _ex( 'Original term:', 'glossary entry', 'glotpress' ); ?></label><dt>
+						<dt><label for="new_glossary_entry_term"><?php esc_html( 'Original term:', 'glossary entry', 'glotpress' ); ?></label></dt>
```
Comment (toolstack) [inline gp-templates/glossary-view.php]: You replaced a translation function with an escaping function, if there was such a thing you would have used `esc_html_ex()`, but since that doesn't exist you'll just have to wrap `_ex()` with `esc_html()`.

File: gp-templates/glossary-view.php [hunk 2]
```diff
@@ -68,7 +68,7 @@
 
 				<form action="<?php echo esc_url( gp_url_join( $url, '-new' ) ); ?>" method="post">
 					<dl>
-						<dt><label for="new_glossary_entry_term"><?php esc_html( 'Original term:', 'glossary entry', 'glotpress' ); ?></label></dt>
+						<dt><label for="new_glossary_entry_term"><?php echo esc_html( _ex( 'Original term:', 'glossary entry', 'glotpress' ) ); ?></label></dt>
```
Comment (toolstack) [inline gp-templates/glossary-view.php]: `_ex()` should only be `_x()` in this case as `_ex()` echos the result instead of returning it ;)

**Review by toolstack — APPROVED** [review]
:+1:
