### PR TITLE
Fix UI inconsistencies

### LINKED ISSUE #99: Improve i18n
Previously: #16 
- [ ] Placeholders aren't explained in a translator comments
- [x] The use of `_n()` is wrong in some cases, like `_n('One translation rejected.', '%d translations rejected.', $ok, 'glotpress' ), $ok );`
- [ ] Strings like `__( 'edit', 'glotpress' )` should get a context:  `_x( 'edit', 'glossary', 'glotpress' )`
- [x] `esc_attr( __( ) )` should be `esc_attr__( )`
- [x] `echo _x( )` should be `_ex( )`

Note: Each point can have its own PR.

### LINKED ISSUE #1209: UI inconsistencies in (actions) and [bubbles] of Projects/Sets/Glossaries
I've made a roundup on some UI inconsistencies that I'll write below:

1. Inconsistent space between project/translation set/glossary title and appended (actions)
2. Translation sets and Glossaries titles have (edit) and (delete) action, while Project titles only have (edit) action
3. Projects and sub-projects lists have [Edit] bubbles but no [Delete] bubbles

The (delete) title actions and [Delete] bubbles links are missing from Projects and Sub-projects by design?
The functions for all of them already exist, just aren't called.

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Fixes #1209

- [x] Fix inconsistent space between project/translation set/glossary title and appended (actions)
- [x] Add (delete) action to Project titles
- [x] Add [Delete] bubbles to Projects and sub-projects lists
- [x] Add missing context to `(edit)` and `(delete)` strings - Fixes #99 
- [x] Bonus: fix capital_P GlotPress

### CODE REVIEW

File: gp-includes/template-links.php [hunk 1]
```diff
@@ -29,7 +29,14 @@ function gp_link_get( $url, $text, $attrs = array() ) {
 	$attributes = gp_html_attributes( $attrs );
 	$attributes = $attributes ? " $attributes" : '';
 
-	return sprintf( '%1$s<a href="%2$s"%3$s>%4$s</a>%5$s', $before, esc_url( $url ), $attributes, $text, $after );
+	return sprintf(
+		'%1$s<a href="%2$s"%3$s>%4$s</a>%5$s',
+		$before,
+		esc_url( $url ),
+		$attributes,
+		' ' . $text,
```
Comment (ocean90) [inline gp-includes/template-links.php]: This doesn't seem right. The space character would also be linked. Looks like the space should be part of the `before` attribute or added to `$before` if it's not empty.

**Review by ocean90 — CHANGES_REQUESTED** [review]
Can you please attach some before/after screenshots?

**Comment by pedro-mendonca** [comment]
Here are the screenshots of the before/after of the change on `gp_link_get()` ( `' ' . $text,`)

**Before:**
imagem

**After:**
imagem

File: gp-includes/template-links.php (hunk 1 above)
Comment (pedro-mendonca) [reply gp-includes/template-links.php:37]: I see, it does really make more sense to add in $before.
I'll wait for you to check the below screenshots before apply this suggestion.

**Comment by pedro-mendonca** [comment]
The space is only missing in Glossary titles. It's ok on Projects and Translation sets.

**Comment by pedro-mendonca** [comment]
@ocean90 I've found the problem that makes it different for Glossary.
It's because of the opening and closing PHP tags that adds space for Projects and Translation sets, and not Glossary.
Pushing a fix in a minute.

File: gp-includes/template-links.php (hunk 1 above)
Comment (pedro-mendonca) [reply gp-includes/template-links.php]: Solved on https://github.com/GlotPress/GlotPress-WP/pull/1210/commits/39ed1ac240e6fb69ecde4388a8f68772bdb39165
